package net.sprocketgames.create_aeronautics_automated_logistics.dock.session;

public enum DockingReason {
    NO_DOCK_CONTEXT,
    LEGACY_ACTIVE_ROUTE,
    LEGACY_UNLOADED_TRANSIT,
    RESERVATION_REQUESTED,
    RESERVATION_QUEUED,
    RESERVATION_GRANTED,
    APPROACH_REACQUIRE,
    CONNECTOR_LOCK_PENDING,
    CONNECTOR_LOCK_CONFIRMED,
    CONDITIONS_ACTIVE,
    DEPARTURE_CLEARANCE,
    PLAYBACK_PAUSED,
    PLAYBACK_FAULTED,
    PLAYBACK_COMPLETED,
    RESTORED_TYPED_SESSION,
    RESTORED_LEGACY_FIELDS,
    INVALID_SAVED_SESSION,
    INCONSISTENT_LEGACY_STATE,
    UNKNOWN
}
