package net.sprocketgames.create_aeronautics_automated_logistics.network;

import net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent;
import net.neoforged.neoforge.network.registration.PayloadRegistrar;

public final class ModNetworking {
    private ModNetworking() {
    }

    public static void register(RegisterPayloadHandlersEvent event) {
        PayloadRegistrar registrar = event.registrar("1");
        registrar.playToServer(
                UpdateIdentityNamePayload.TYPE,
                UpdateIdentityNamePayload.STREAM_CODEC,
                UpdateIdentityNamePayload::handle
        );
        registrar.playToServer(
                UpdateAirshipScheduleTitlePayload.TYPE,
                UpdateAirshipScheduleTitlePayload.STREAM_CODEC,
                UpdateAirshipScheduleTitlePayload::handle
        );
        registrar.playToServer(
                UpdateAirshipSchedulePayload.TYPE,
                UpdateAirshipSchedulePayload.STREAM_CODEC,
                UpdateAirshipSchedulePayload::handle
        );
        registrar.playToServer(
                SelectAirshipScheduleStationPayload.TYPE,
                SelectAirshipScheduleStationPayload.STREAM_CODEC,
                SelectAirshipScheduleStationPayload::handle
        );
        registrar.playToServer(
                OpenInstalledScheduleEditorPayload.TYPE,
                OpenInstalledScheduleEditorPayload.STREAM_CODEC,
                OpenInstalledScheduleEditorPayload::handle
        );
        registrar.playToServer(
                ReopenShipTransponderPayload.TYPE,
                ReopenShipTransponderPayload.STREAM_CODEC,
                ReopenShipTransponderPayload::handle
        );
        registrar.playToServer(
                StartTransponderRouteRecordingPayload.TYPE,
                StartTransponderRouteRecordingPayload.STREAM_CODEC,
                StartTransponderRouteRecordingPayload::handle
        );
        registrar.playToServer(
                FinishTransponderRouteRecordingPayload.TYPE,
                FinishTransponderRouteRecordingPayload.STREAM_CODEC,
                FinishTransponderRouteRecordingPayload::handle
        );
        registrar.playToServer(
                CancelTransponderRouteRecordingPayload.TYPE,
                CancelTransponderRouteRecordingPayload.STREAM_CODEC,
                CancelTransponderRouteRecordingPayload::handle
        );
        registrar.playToServer(
                SetTransponderAppendModePayload.TYPE,
                SetTransponderAppendModePayload.STREAM_CODEC,
                SetTransponderAppendModePayload::handle
        );
        registrar.playToClient(
                SetFlightPathPreviewPayload.TYPE,
                SetFlightPathPreviewPayload.STREAM_CODEC,
                SetFlightPathPreviewPayload::handle
        );
        registrar.playToClient(
                SetAutomatedShipVisualStatePayload.TYPE,
                SetAutomatedShipVisualStatePayload.STREAM_CODEC,
                SetAutomatedShipVisualStatePayload::handle
        );
        registrar.playToClient(
                SyncAutomatedShipVisualsPayload.TYPE,
                SyncAutomatedShipVisualsPayload.STREAM_CODEC,
                SyncAutomatedShipVisualsPayload::handle
        );
        registrar.playToClient(
                SetDockLinkPromptPayload.TYPE,
                SetDockLinkPromptPayload.STREAM_CODEC,
                SetDockLinkPromptPayload::handle
        );
        registrar.playToClient(
                SetCargoLinkPromptPayload.TYPE,
                SetCargoLinkPromptPayload.STREAM_CODEC,
                SetCargoLinkPromptPayload::handle
        );
        registrar.playToClient(
                SetMenuActionBarMessagePayload.TYPE,
                SetMenuActionBarMessagePayload.STREAM_CODEC,
                SetMenuActionBarMessagePayload::handle
        );
        registrar.playToClient(
                SetTransponderRecordingStatePayload.TYPE,
                SetTransponderRecordingStatePayload.STREAM_CODEC,
                SetTransponderRecordingStatePayload::handle
        );
        registrar.playToClient(
                SyncTransponderOwnedSchedulePayload.TYPE,
                SyncTransponderOwnedSchedulePayload.STREAM_CODEC,
                SyncTransponderOwnedSchedulePayload::handle
        );
        registrar.playToClient(
                SyncStationRouteChoicesPayload.TYPE,
                SyncStationRouteChoicesPayload.STREAM_CODEC,
                SyncStationRouteChoicesPayload::handle
        );
        registrar.playToClient(
                SyncStationMenuStatePayload.TYPE,
                SyncStationMenuStatePayload.STREAM_CODEC,
                SyncStationMenuStatePayload::handle
        );
    }
}
